### ISSUE TITLE
**Class Structure**

### ISSUE THREAD

**Issue by amstone2** [mucsci-students/2021sp-420-Team-Indecision#13]
- [x] Determine the structure of the Class object/class
 - [x] Determine the structure of the Attribute object/class
 - [x] Determine the structure of the Relationships object/class

 - @cjnissle 

 - Size: L
 - Actual Size: (fib number after completion) L
 - Actual Time: (in minutes or hours -- after completion) 6 hours

**Comment by cjnissle** [comment]
Completed. Added Class prototype to develop.
