### ISSUE TITLE
**Data Storage**

### ISSUE THREAD

**Issue by amstone2** [mucsci-students/2021sp-420-Team-Indecision#14]
- [x] Determine how the Class data will be stored.
 - [x] Determine how the Attribute data will be stored.
 - [x] Determine how the Relationship data will be stored.

 - @cjnissle

 - Size: L
 - Actual Size: (fib number after completion)
 - Actual Time: (in minutes or hours -- after completion)

**Comment by cjnissle** [comment]
Completed.
