### ISSUE TITLE
Parameter input within the GUI is janky/ambiguous

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2021sp-420-Team-Indecision#76]
The first prompt says to enter parameters
<img width="501" alt="Screen Shot 2021-03-08 at 10 33 51 AM" src="https://user-images.githubusercontent.com/2007799/110342949-f9d4f700-7ff9-11eb-9c7c-b3aadbc26f38.png">

But then I'm asked if I want to enter more!?!?!
<img width="469" alt="Screen Shot 2021-03-08 at 10 34 05 AM" src="https://user-images.githubusercontent.com/2007799/110342965-fccfe780-7ff9-11eb-9510-7b690d37f773.png">

This usage is not obvious or clear.

**Comment by cjnissle** [comment]
This process is now less ambiguous.

**Comment by willkill07** [comment]
(note: coming from not-the-client)

For this (and other issues) you should probably mention the issue number and say that a PR closes this issue within a git commit message or as a comment on the PR. If it was already merged, than this issue must be manually closed.

**Comment by cjnissle** [comment]
Closed with PR #78.

**Comment by willkill07** [comment]
This has not been resolved.
